CREATE TABLE IF NOT EXISTS users(
  user_id VARCHAR(36) PRIMARY KEY,
  name VARCHAR (50) UNIQUE NOT NULL,
  email VARCHAR (256) UNIQUE NOT NULL
  password VARCHAR (50) NOT NULL,
  created TIMESTAMP NOT NULL,
);
